version: '3.9'
services:
  web-dev:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    environment:
      - TABULA_URI=http://localhost:8081/iiif/peutinger.jp2/info.json
    profiles:
      - dev

  web:
    build: .
    ports:
      - "8080:80"
    profiles:
      - prod

  iipsrv:
    image: iipsrv/iipsrv
    ports:
      - "8081:80"
    volumes:
      - ./images/:/images
    environment:
    - CORS=*
    restart: always
    profiles:
      - dev
      - prod

